Add security-updates-only configuration for renovate
laminas/.github pull request #35
Opened 2022-09-13 16:59 UTC by internalsystemerror

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | yes

### Description

As discussed at the [September 12th 2022 meeting](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2022-09-12-TSC-Minutes.md#security-only-packages-and-dependency-updates) of the TSC, we intend to roll out renovate for "security-updates-only" repositories of Laminas.

This PR:
- adds the shared configuration for use in those repositories
- fixes a minor documentation typo (missing closing **)
- adds documentation for the new configuration
- updates renovates owner from Whitesource to Mend as noted at https://github.com/whitesource

2022-09-14 18:55 UTC, Ocramius commented
@internalsystemerror wrong branch deleted? 🤔

2022-09-14 18:56 UTC, internalsystemerror commented
ahhhhhhhhh bugger ... i already left now too :/ dnt suppose u still haz? 🤣

2022-09-15 13:28 UTC, internalsystemerror commented
restored.

2022-10-31 16:09 UTC, Ocramius requested changes

2022-10-31 16:09 UTC, Ocramius commented on renovate-config-security-updates-only.json
> +        {"matchPackageNames": ["php"], "enabled": true, "rangeStrategy": "widen"}
Should we create draft MRs to widen the PHP version also here?

2022-10-31 17:26 UTC, internalsystemerror commented on renovate-config-security-updates-only.json
> +        {"matchPackageNames": ["php"], "enabled": true, "rangeStrategy": "widen"}
This extends the default, so should inherit the specifics from that, meaning we could remove the "rangeStrategy": "widen" part and only need to disable all packages except for PHP. I will update.

2022-10-31 17:37 UTC, internalsystemerror commented
It no longer seems to be tracking the branch on my fork, should I close this and reopen?

2022-10-31 22:51 UTC, Ocramius commented
If you think it has an effect: sure!

2022-11-01 00:28 UTC, closed without merging