Bump `require-dev` instead of `widen`
laminas/.github pull request #39
Opened 2022-10-31 16:31 UTC by gsteel

|    Q          |   A
|-------------- | ------
| New Feature   | yes

Further to https://github.com/laminas/.github/pull/37#issuecomment-1297256035

2022-10-31 16:32 UTC, Ocramius approved these changes
LGTM. @internalsystemerror should cross-check though :)

2022-10-31 17:20 UTC, internalsystemerror commented
The default is set to replace and then is overriden specifically for "require". I would change the default instead of adding another package rule:
https://github.com/laminas/.github/blob/de7b1c5d5ca9e18162d28754697a40a22791cce4/renovate-config.json#L23

The documentation for that would also need updating. Happy to go with this! The original use of "replace" was simply to reduce the noise.

2022-10-31 17:23 UTC, internalsystemerror requested changes

2022-10-31 17:23 UTC, internalsystemerror commented on RENOVATE.md
> +    {"matchDepTypes": ["require-dev"], "rangeStrategy": "bump"},
Modify the default instead of adding this rule

2022-10-31 17:23 UTC, internalsystemerror commented on RENOVATE.md
>      {"matchDepTypes": ["require"], "rangeStrategy": "widen"},
We may also want to add "dependencies" to the "matchDepTypes" array here but I can do that in another PR.

2022-10-31 17:23 UTC, internalsystemerror commented on RENOVATE.md
>   - `replace` Replace the range with a newer one if the new version falls outside it, and update nothing otherwise.
This line would also need changing to reflect the use of bump instead of replace.

2022-10-31 17:23 UTC, internalsystemerror commented on renovate-config.json
> +        {"matchDepTypes": ["require-dev"], "rangeStrategy": "bump"},
And here, modify the default rangeStrategy instead of adding another package rule.

2022-11-01 08:48 UTC, Ocramius approved these changes
:ship:

2022-11-01 08:49 UTC, merged

2022-11-01 09:51 UTC, Ocramius commented
FWIW, this is starting to work, but the fact that renovate doesn't respect dependency ranges makes **all** bumps fail 😬

2022-11-01 10:05 UTC, gsteel commented
Perhaps the failures relate to this: https://github.com/mezzio/mezzio-authorization-acl/pull/23#issuecomment-1298297654

2022-11-01 11:18 UTC, internalsystemerror commented
@Ocramius Did you mean renovate there or automatic-releases? If the former, can you ping me on one so I can take a closer look?

2022-11-01 11:30 UTC, Ocramius commented
All of these (sorry, posting screenshot because I'm in a hurry today): 

![Selection_1061](https://user-images.githubusercontent.com/154256/199223237-19cce622-7498-46b8-9a00-619350d81067.png)

Renovate performs an `bump` as we did here, but:

 * does not use `-W` while doing so
 * does not respect `config.platform.php`

2022-11-01 11:56 UTC, internalsystemerror commented
> does not use -W while doing so
Correct and confirmed, it's running with `--with-dependencies`, however that shouldn't be an issue as we have lock file maintenance running daily and the update command here is simply to update the lock file.

> does not respect `config.platform.php`
It's definitely running these with the correct PHP version (I've checked the logs for the top few of these), but I think I understand your point as, it's recommending updates that aren't compatible with the PHP version we're running.

From my understanding, renovate will suggest updates for any newer version regardless of what it is. Because it's not compatible it will also fail and add a commenting saying what the incompatibility problem is. 

As I understand it (which may be wrong), the updates to `composer.json` are done using regex essentially and then the updates to `composer.lock` are done using composer. I'll try to figure out what exactly is going on here and seek help from the renovate team for clarification.

2022-11-01 15:24 UTC, Ocramius commented
I raised #41 to track the issue in more detail.